import React from "react"
import { QuizItem } from "../../App"

export const Items: QuizItem[] = [
    {pic: <img src={require("./assets/aeshna_a.png")}/>, answer: "Aeshna affinis"},
    {pic: <img src={require("./assets/aeshna_c.png")}/>, answer: "Aeshna cyanea"},
    {pic: <img src={require("./assets/aeshna_v.png")}/>, answer: "Aeshna viridis"},
    {pic: <img src={require("./assets/anax_i.png")}/>, answer: "Anax imperator"},
    {pic: <img src={require("./assets/cordulegaster_h.png")}/>, answer: "Cordulegaster heros"},
    {pic: <img src={require("./assets/crocotemhis_e.png")}/>, answer: "Crocothemis erythraea"},
    {pic: <img src={require("./assets/libelulla_d.png")}/>, answer: "Libellula depressa"},
    {pic: <img src={require("./assets/libelulla_q.png")}/>, answer: "Libellula quadrimaculata"},
    {pic: <img src={require("./assets/ophiogomphus_c.png")}/>, answer: "Ophiogomphus cecilia"},
    {pic: <img src={require("./assets/orthoretrum_c.png")}/>, answer: "Orthetrum coerulescens"},
    {pic: <img src={require("./assets/somatochlora_m.png")}/>, answer: "Somatochlora metallica"},
    {pic: <img src={require("./assets/sympetrum_v.png")}/>, answer: "Sympetrum vulgatum"},
    {pic: <img src={require("./assets/calopteryx_s.png")}/>, answer: "Calopteryx splendens"},
    {pic: <img src={require("./assets/calopteryx_v.png")}/>, answer: "Calopteryx virgo"},
    {pic: <img src={require("./assets/chalcolestes_p.png")}/>, answer: "Chalcolestes parvidens"},
    {pic: <img src={require("./assets/coenagrion_o.png")}/>, answer: "Coenagrion ornatum"},
    {pic: <img src={require("./assets/enallagma_c.png")}/>, answer: "Enallagma cyathigerum"},
    {pic: <img src={require("./assets/ischnura_e.png")}/>, answer: "Ischnura elegans"},
    {pic: <img src={require("./assets/lestes_s.png")}/>, answer: "Lestes sponsa"},
    {pic: <img src={require("./assets/lestes_v.png")}/>, answer: "Lestes virens"},
    {pic: <img src={require("./assets/platycnemis_p.png")}/>, answer: "Platycnemis pennipes"},
    {pic: <img src={require("./assets/pyrrhosoma_n.png")}/>, answer: "Pyrrhosoma nymphula"},
    {pic: <img src={require("./assets/sympecna_f.png")}/>, answer: "Sympecma fusca"},
    {pic: <img src={require("./assets/ephemera_v.png")}/>, answer: "Ephemera vulgata"},
    {pic: <img src={require("./assets/palingenia_l.png")}/>, answer: "Palingenia longicauda"},
    {pic: <img src={require("./assets/sympterum_s.png")}/>, answer: "Sympetrum sanguineum"},
    {pic: <img src={require("./assets/perla_m.png")}/>, answer: "Perla maxima"},
    {pic: <img src={require("./assets/forficula_a.png")}/>, answer: "Forficula auricularia"},
    {pic: <img src={require("./assets/mantis_r.png")}/>, answer: "Mantis religiosa"},
    {pic: <img src={require("./assets/periplaneta_a.png")}/>, answer: "Periplaneta americana"},
    {pic: <img src={require("./assets/blatta_o.png")}/>, answer: "Blatta orientalis"},
    {pic: <img src={require("./assets/blatella_g.png")}/>, answer: "Blattella germanica"},
    {pic: <img src={require("./assets/ectobius_s.png")}/>, answer: "Ectobius sylvestris"},
]