import React from "react"
import { QuizItem } from "../../App"

export const Items: QuizItem[] = [
    {pic: <img src={require("./assets/xyela.png")}/>, answer: "Xyela"},
    {pic: <img src={require("./assets/cephus_p.png")}/>, answer: "Cephus Pygmacus"},
    {pic: <img src={require("./assets/rhogogaster_v.png")}/>, answer: "Rhogogaster viridis"},
    {pic: <img src={require("./assets/athalia_r.png")}/>, answer: "Athalia Rosae"},
    {pic: <img src={require("./assets/uroceros_gigas.png")}/>, answer: "Urocerus Gigas"},
    {pic: <img src={require("./assets/andricus_h.png")}/>, answer: "Andricus hungaricus"},
    {pic: <img src={require("./assets/andricus_q.png")}/>, answer: "Andricus quercuscalicis"},
    {pic: <img src={require("./assets/ichneumon.png")}/>, answer: "Ichneumon"},
    {pic: <img src={require("./assets/rhyssa.png")}/>, answer: "Rhyssa persuasoria"},
    {pic: <img src={require("./assets/ophion.png")}/>, answer: "Ophion"},
    {pic: <img src={require("./assets/cotesia.png")}/>, answer: "Cotesia glomerata"},
    {pic: <img src={require("./assets/chrysis.png")}/>, answer: "Chrysis"},
    {pic: <img src={require("./assets/megascolia.png")}/>, answer: "Megascolia maculata"},
    {pic: <img src={require("./assets/mutilla.png")}/>, answer: "Mutilla"},
    {pic: <img src={require("./assets/pompilus.png")}/>, answer: "Pompilus"},
    {pic: <img src={require("./assets/eumenes.png")}/>, answer: "Eumenes coarctatus"},
    {pic: <img src={require("./assets/polistes.png")}/>, answer: "Polistes gallicus"},
    {pic: <img src={require("./assets/vespula_g.png")}/>, answer: "Vespula germanica"},
    {pic: <img src={require("./assets/vespula_v.png")}/>, answer: "Vespula vulgaris"},
    {pic: <img src={require("./assets/vespa_c.png")}/>, answer: "Vespa crabro"},
    {pic: <img src={require("./assets/monomorium_p.png")}/>, answer: "Monomorium pharaonis"},
    {pic: <img src={require("./assets/tetramorium_c.png")}/>, answer: "Tetramorium caespitum"},
    {pic: <img src={require("./assets/formica_c.png")}/>, answer: "Formica cunicularia"},
    {pic: <img src={require("./assets/formica_r.png")}/>, answer: "Formica rufa"},
    {pic: <img src={require("./assets/lasius_n.png")}/>, answer: "Lasius niger"},
    {pic: <img src={require("./assets/ammophila_s.png")}/>, answer: "Ammophila sabulosa"},
    {pic: <img src={require("./assets/sceliphron_d.png")}/>, answer: "Sceliphron destillatorium"},
    {pic: <img src={require("./assets/philanthus_t.png")}/>, answer: "Philanthus triangulum"},
    {pic: <img src={require("./assets/andrena.png")}/>, answer: "Andrena"},
    {pic: <img src={require("./assets/halictus.png")}/>, answer: "Halictus"},
    {pic: <img src={require("./assets/megachile.png")}/>, answer: "Megachile"},
    {pic: <img src={require("./assets/xylocopa_v.png")}/>, answer: "Xylocopa violacea"},
    {pic: <img src={require("./assets/bombus_p.png")}/>, answer: "Bombus pascuorum"},
    {pic: <img src={require("./assets/bombus_l.png")}/>, answer: "Bombus lapidarius"},
    {pic: <img src={require("./assets/bombus_r.png")}/>, answer: "Bombus rupestris"},
    {pic: <img src={require("./assets/apis_m.png")}/>, answer: "Apis mellifera"},    
]